x-common-env: &common-env
  HUMHUB_CONFIG__COMPONENTS__DB__USERNAME: ${HUMHUB_DOCKER_DB_USER}
  HUMHUB_CONFIG__COMPONENTS__DB__PASSWORD: ${HUMHUB_DOCKER_DB_PASSWORD}
  HUMHUB_FIXED_SETTINGS__BASE__CACHE_CLASS: yii\redis\Cache
  HUMHUB_CONFIG__COMPONENTS__REDIS__CLASS: yii\redis\Connection
  HUMHUB_CONFIG__COMPONENTS__REDIS__HOSTNAME: redis
  HUMHUB_CONFIG__COMPONENTS__REDIS__PORT: 6379
  HUMHUB_CONFIG__COMPONENTS__SESSION__CLASS: yii\redis\Session

services:
  humhub_development:
    build:
      context: ./image
      tags:
        - 216989108086.dkr.ecr.us-east-2.amazonaws.com/moser-inc/mhai-humhub:${HUMHUB_DOCKER_VERSION}-${MHAI_DOCKER_IMAGE_VERSION}
        - 216989108086.dkr.ecr.us-east-2.amazonaws.com/moser-inc/mhai-humhub:latest
    image: moser-inc/mhai-humhub:latest
    ports:
      - 8804:8404
    volumes:
      - ./:/host
      - ./humhub-data:/var/lib/humhub
    env_file:
      - ./humhub.env
    environment:
      HUMHUB_CONFIG__COMPONENTS__DB__DSN: ${HUMHUB_MW_DSN}
      HUMHUB_FIXED_SETTINGS__BASE__BASE_URL: https://${HUMHUB_MW_DOMAIN}
      HUMHUB_CONFIG__COMPONENTS__REDIS__DATABASE: 0
      <<: *common-env

